trigger:
- main

pool:
  vmImage: windows-2019

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Demo Account'
    ScriptType: 'InlineScript'
    Inline: |
      Install-Module -Name Az.PostgreSql -Scope CurrentUser -Force
    preferredAzurePowerShellVersion: '6.4.0'
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Demo Account'
    ScriptType: 'InlineScript'
    Inline: |
      import-module az;
      Update-AzPostgreSqlServer -Name TBD -ResourceGroupName TBD -ReplicationRole None;
    preferredAzurePowerShellVersion: '6.4.0'
